project_id = "happyhour"

[api]
enabled = true
port = 54321
schemas = ["public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["happyhour://"]

[auth.external.apple]
enabled = false

[auth.external.google]
enabled = false
